global:
  scrape_interval: 5s  # Scrape metrics every 15 seconds
  scrape_timeout: "3s"
  evaluation_interval: "5s"

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: 
        - '192.168.5.33:9100'
        
  - job_name: "echo-api"
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets:
        - 'echo-api:8081'
    basic_auth:
      username: "admin"
      password: "admin"