global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds
  scrape_timeout: "10s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: 
        - 'node-exporter:9100'
        
  - job_name: "echo-api"
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets:
        - 'echo-api:8081'
    basic_auth:
      username: "admin"
      password: "admin"